### ISSUE TITLE
[auth] implement SSO and / or oauth

### ISSUE THREAD

**Issue by Logannford** [Logannford/TechBlitz#261]
I know you'll like this @jakemackie 😉 
https://supabase.com/docs/guides/auth/social-login/auth-github

- github
- apple
- google
- facebook

**Comment by jakemackie** [comment]
Hell yeah

**Comment by jakemackie** [comment]
I will say with this comes the issue of password resets. I would prompt the user to create a password after a successful sign in with any provider @Logannford
