### ISSUE TITLE
[frontend] FAQs

### ISSUE THREAD

**Issue by jakemackie** [Logannford/TechBlitz#299]
<img width="1091" alt="Screenshot 2024-12-19 at 12 21 28" src="https://github.com/user-attachments/assets/4c867694-bfce-41ea-83d4-149b81558a75" />

I just think & feel as though this is repeating itself? Also the padding doesn't feel right - I hate to open this one but hopefully you see what I mean

**Comment by Logannford** [comment]
@jakemackie yeah good shout - I will remove
